### ISSUE TITLE
Wrong comment format in PHP files

### ISSUE THREAD

**Issue by roblesterjr04** [tommasongr/nova-copyright#1]
PHP files expect the `//` comment format, but your tool returns `<!--` comments.

This could work in rudimentary php script files, but when working with an application, php devs prefer php comments. The html style comments would render on the page output if they were put outside the php tag.

**Comment by tommasongr** [comment]
Hi there! Thanks for the clarification 😄

I never looked in depth at PHP so thanks for this hint. I'll fix it ASAP

**Comment by tommasongr** [comment]
Fixed in v1.1
